//! Step 5: build a real `.deb`.
//!
//! Generated capabilities are packages rather than loose files because that is
//! what makes them undoable, explainable and copyable: `apt remove` undoes,
//! `dpkg -l` explains, and copying the file moves the capability to another
//! machine. Building a bespoke installer would mean reimplementing all three,
//! worse.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

pub struct PackageSpec {
    pub name: String,
    pub version: String,
    pub description: String,
    /// Files to install, as (path inside the package, contents).
    pub files: Vec<(String, String)>,
    /// Files that must be executable.
    pub executable: Vec<String>,
}

#[derive(Debug)]
pub enum PackageError {
    Io(std::io::Error),
    Build(String),
    /// dpkg-deb is not installed. Named specifically because the fix is one
    /// apt install and a generic "command failed" would hide that.
    NoDpkgDeb,
}

impl std::fmt::Display for PackageError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PackageError::Io(e) => write!(f, "{e}"),
            PackageError::Build(what) => write!(f, "dpkg-deb failed: {what}"),
            PackageError::NoDpkgDeb => {
                write!(f, "dpkg-deb is not installed (apt install dpkg-dev)")
            }
        }
    }
}

impl From<std::io::Error> for PackageError {
    fn from(e: std::io::Error) -> Self {
        PackageError::Io(e)
    }
}

impl PackageSpec {
    /// Lay out the package tree and build it. Returns the path to the `.deb`.
    pub fn build(&self, workdir: &Path) -> Result<PathBuf, PackageError> {
        let root = workdir.join(&self.name);
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("DEBIAN"))?;

        for (path, contents) in &self.files {
            let target = root.join(path.trim_start_matches('/'));
            if let Some(parent) = target.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(&target, contents)?;
            if self.executable.contains(path) {
                set_executable(&target)?;
            }
        }

        fs::write(root.join("DEBIAN/control"), self.control())?;

        let output = Command::new("dpkg-deb")
            .args(["--root-owner-group", "--build"])
            .arg(&root)
            .arg(workdir)
            .output()
            .map_err(|e| {
                if e.kind() == std::io::ErrorKind::NotFound {
                    PackageError::NoDpkgDeb
                } else {
                    PackageError::Io(e)
                }
            })?;

        if !output.status.success() {
            return Err(PackageError::Build(
                String::from_utf8_lossy(&output.stderr).trim().to_string(),
            ));
        }

        let deb = workdir.join(format!("{}_{}_all.deb", self.name, self.version));
        if deb.exists() {
            return Ok(deb);
        }
        // dpkg-deb names the file from the control fields; find it rather than
        // assuming, so an architecture change does not break this silently.
        fs::read_dir(workdir)?
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .find(|p| p.extension().is_some_and(|ext| ext == "deb"))
            .ok_or_else(|| PackageError::Build("no .deb was produced".into()))
    }

    fn control(&self) -> String {
        // Architecture: all because a capability is configuration and scripts,
        // not compiled code. That also means it copies to an arm64 board from
        // an amd64 desktop unchanged.
        format!(
            "Package: {}\n\
             Version: {}\n\
             Section: admin\n\
             Priority: optional\n\
             Architecture: all\n\
             Maintainer: Omnia OS <omnia@localhost>\n\
             Description: {}\n\
             \x20Generated by Omnia and kept only because its test passed.\n",
            self.name, self.version, self.description
        )
    }
}

fn set_executable(path: &Path) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    let mut permissions = fs::metadata(path)?.permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(path, permissions)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_package_is_actually_built_and_readable_by_dpkg() {
        let workdir = std::env::temp_dir().join(format!("omnia-pkg-test-{}", std::process::id()));
        let _ = fs::remove_dir_all(&workdir);
        fs::create_dir_all(&workdir).unwrap();

        let spec = PackageSpec {
            name: "omnia-cap-backup-pictures".into(),
            version: "1.0.0".into(),
            description: "Back up ~/Pictures nightly".into(),
            files: vec![
                (
                    "/lib/systemd/system/omnia-cap-backup-pictures.service".into(),
                    "[Unit]\nDescription=test\n".into(),
                ),
                (
                    "/usr/share/omnia/capabilities/backup-pictures/test.sh".into(),
                    "#!/bin/sh\n".into(),
                ),
            ],
            executable: vec!["/usr/share/omnia/capabilities/backup-pictures/test.sh".into()],
        };

        let deb = match spec.build(&workdir) {
            Ok(deb) => deb,
            Err(PackageError::NoDpkgDeb) => {
                let _ = fs::remove_dir_all(&workdir);
                return; // nothing to assert on a machine without dpkg-deb
            }
            Err(e) => panic!("build failed: {e}"),
        };
        assert!(deb.exists(), "the .deb must exist at {}", deb.display());

        // Read it back with dpkg itself rather than trusting our own writer.
        let listing = Command::new("dpkg-deb")
            .arg("--contents")
            .arg(&deb)
            .output()
            .unwrap();
        let listing = String::from_utf8_lossy(&listing.stdout);
        assert!(
            listing.contains("omnia-cap-backup-pictures.service"),
            "{listing}"
        );

        let info = Command::new("dpkg-deb")
            .arg("--field")
            .arg(&deb)
            .arg("Package")
            .output()
            .unwrap();
        assert_eq!(
            String::from_utf8_lossy(&info.stdout).trim(),
            "omnia-cap-backup-pictures"
        );

        let _ = fs::remove_dir_all(&workdir);
    }
}
