//! Rendering a systemd unit from a permission set.

use std::fmt::Write as _;

use omnia_parts::Permissions;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnitKind {
    /// Runs once when started.
    OneShot,
    /// Runs on a timer. The timer unit is rendered separately.
    Scheduled,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Unit {
    pub name: String,
    pub description: String,
    pub kind: UnitKind,
    pub argv: Vec<String>,
    pub permissions: Permissions,
}

impl Unit {
    /// Render the `.service` file.
    ///
    /// Every directive here is deliberate, and the ones that are absent are
    /// deliberate too. The comments in the output are for the operator reading
    /// `systemctl cat`, not for us.
    pub fn render_service(&self) -> String {
        let mut out = String::new();

        let _ = writeln!(
            out,
            "# Generated by Omnia. Do not edit: regenerated on rebuild."
        );
        let _ = writeln!(
            out,
            "# Reach is derived from the parts used, not declared by a model."
        );
        let _ = writeln!(out, "[Unit]");
        let _ = writeln!(out, "Description={}", self.description);
        let _ = writeln!(out, "Documentation=man:omni(1)");
        let _ = writeln!(out);

        let _ = writeln!(out, "[Service]");
        let _ = writeln!(out, "Type=oneshot");
        let _ = writeln!(out, "ExecStart={}", quote_argv(&self.argv));
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- filesystem ---");
        // strict: everything read-only except /dev, /proc, /sys, then the
        // write paths are punched back in explicitly below.
        let _ = writeln!(out, "ProtectSystem=strict");
        let _ = writeln!(out, "ProtectHome={}", self.protect_home());
        if !self.permissions.read_paths.is_empty() {
            let _ = writeln!(out, "ReadOnlyPaths={}", join(&self.permissions.read_paths));
        }
        if !self.permissions.write_paths.is_empty() {
            let _ = writeln!(
                out,
                "ReadWritePaths={}",
                join(&self.permissions.write_paths)
            );
        }
        let _ = writeln!(out, "PrivateTmp=yes");
        let _ = writeln!(out, "ProtectProc=invisible");
        let _ = writeln!(out, "ProcSubset=pid");
        let _ = writeln!(out, "UMask=0077");
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- network ---");
        if self.permissions.network {
            let _ = writeln!(out, "# this capability declared network access");
            let _ = writeln!(out, "PrivateNetwork=no");
            let _ = writeln!(out, "RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX");
        } else {
            // The strongest available statement: no network namespace at all.
            let _ = writeln!(out, "PrivateNetwork=yes");
            let _ = writeln!(out, "RestrictAddressFamilies=AF_UNIX");
            let _ = writeln!(out, "IPAddressDeny=any");
        }
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- privilege ---");
        let _ = writeln!(out, "NoNewPrivileges=yes");
        let _ = writeln!(out, "CapabilityBoundingSet=");
        let _ = writeln!(out, "AmbientCapabilities=");
        let _ = writeln!(out, "RestrictSUIDSGID=yes");
        let _ = writeln!(out, "PrivateUsers=yes");
        let _ = writeln!(out, "DynamicUser=no");
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- kernel ---");
        let _ = writeln!(out, "ProtectKernelTunables=yes");
        let _ = writeln!(out, "ProtectKernelModules=yes");
        let _ = writeln!(out, "ProtectKernelLogs=yes");
        let _ = writeln!(out, "ProtectControlGroups=yes");
        let _ = writeln!(out, "ProtectClock=yes");
        let _ = writeln!(out, "ProtectHostname=yes");
        let _ = writeln!(out, "RestrictNamespaces=yes");
        let _ = writeln!(out, "RestrictRealtime=yes");
        let _ = writeln!(out, "LockPersonality=yes");
        let _ = writeln!(out, "MemoryDenyWriteExecute=yes");
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- devices ---");
        if self.permissions.devices.is_empty() {
            // A private /dev with only the standard pseudo-devices. Nothing
            // this capability does involves hardware.
            let _ = writeln!(out, "PrivateDevices=yes");
            let _ = writeln!(out, "DevicePolicy=closed");
        } else {
            // PrivateDevices=yes would mount a /dev containing only null, zero,
            // random and friends -- and the device this driver exists to drive
            // would simply not be there. The failure is a confusing ENOENT
            // rather than a permission error, so it is worth saying out loud in
            // the unit itself.
            let _ = writeln!(
                out,
                "# This capability drives hardware. PrivateDevices=yes would hide"
            );
            let _ = writeln!(
                out,
                "# the device from its own driver, so /dev is real and the policy"
            );
            let _ = writeln!(out, "# below is what narrows it to one node.");
            let _ = writeln!(out, "PrivateDevices=no");
            // closed: the standard pseudo-devices plus whatever is allowed
            // below, and nothing else on the machine.
            let _ = writeln!(out, "DevicePolicy=closed");
            for node in &self.permissions.devices {
                let _ = writeln!(out, "DeviceAllow={node} rw");
            }
        }
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- syscalls ---");
        let _ = writeln!(out, "SystemCallArchitectures=native");
        // Two lines, not one, and this is not a style choice.
        //
        // `SystemCallFilter=@system-service ~@privileged ~@module` looks like
        // it means "allow @system-service, minus those groups". It does not.
        // systemd parses a leading `~` as making the *whole line* a deny-list,
        // and a `~` on an individual item is not syntax at all: it logs
        // "System call ~@privileged is not known, ignoring" and drops it. The
        // unit then ships with none of the narrowing it appears to declare.
        //
        // Nothing in the unit's text shows this. It was found by running the
        // generated file through `systemd-analyze verify`, which is why that is
        // now a test.
        //
        // The allow-list comes first and the deny-list subtracts from it. ioctl
        // is inside @system-service and survives both: it is how a userspace
        // driver talks to usbfs and to an I2C bus, and losing it would leave a
        // driver that can open its device and do nothing with it.
        let _ = writeln!(out, "SystemCallFilter=@system-service");
        let _ = writeln!(
            out,
            "SystemCallFilter=~@privileged @resources @mount @debug @module"
        );
        let _ = writeln!(out, "SystemCallErrorNumber=EPERM");

        out
    }

    /// Render the `.timer` file. `None` for capabilities that are not scheduled.
    pub fn render_timer(&self, calendar: &str) -> Option<String> {
        if self.kind != UnitKind::Scheduled {
            return None;
        }
        let mut out = String::new();
        let _ = writeln!(
            out,
            "# Generated by Omnia. Do not edit: regenerated on rebuild."
        );
        let _ = writeln!(out, "[Unit]");
        let _ = writeln!(out, "Description={} (timer)", self.description);
        let _ = writeln!(out);
        let _ = writeln!(out, "[Timer]");
        let _ = writeln!(out, "OnCalendar={calendar}");
        // A machine that was asleep at 02:00 still wants its backup.
        let _ = writeln!(out, "Persistent=yes");
        // Without this every machine in a fleet runs at exactly 02:00:00.
        let _ = writeln!(out, "RandomizedDelaySec=300");
        let _ = writeln!(out);
        let _ = writeln!(out, "[Install]");
        let _ = writeln!(out, "WantedBy=timers.target");
        Some(out)
    }

    /// `ProtectHome` depends on where the capability needs to write.
    ///
    /// Getting this wrong is silent: `read-only` with a write target under home
    /// produces a unit that starts fine and fails every run with EROFS. So the
    /// value is computed from the paths rather than fixed.
    fn protect_home(&self) -> &'static str {
        let writes_under_home = self
            .permissions
            .write_paths
            .iter()
            .any(|p| is_under_home(p));
        let reads_under_home = self.permissions.read_paths.iter().any(|p| is_under_home(p));

        if writes_under_home {
            // ReadWritePaths punches through, but ProtectHome must not be
            // masking the tree in the first place.
            "no"
        } else if reads_under_home {
            "read-only"
        } else {
            // Nothing in home is needed, so hide it entirely.
            "yes"
        }
    }
}

fn is_under_home(path: &str) -> bool {
    path.starts_with("/home/") || path.starts_with("/root/") || path.starts_with("~/")
}

/// Paths in systemd directives are space-separated; a path containing a space
/// is quoted.
fn join(paths: &[String]) -> String {
    paths
        .iter()
        .map(|p| {
            if p.contains(' ') {
                format!("\"{p}\"")
            } else {
                p.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Render argv for `ExecStart`. systemd splits on whitespace unless quoted, so
/// any element containing a space or a quote is quoted and escaped.
fn quote_argv(argv: &[String]) -> String {
    argv.iter()
        .map(|arg| {
            if arg.contains(' ') || arg.contains('"') || arg.contains('\\') {
                format!("\"{}\"", arg.replace('\\', "\\\\").replace('"', "\\\""))
            } else {
                arg.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod systemd_tests {
    use super::*;

    /// Run a rendered unit through systemd's own parser.
    ///
    /// Asserting on substrings proves the text is there, not that systemd
    /// understands it. The SystemCallFilter syntax bug this test was written
    /// for passed every substring assertion in this file while systemd silently
    /// discarded five deny-groups — the unit shipped without the narrowing it
    /// appeared to declare, and nothing in the file showed it.
    ///
    /// Returns systemd's complaints, minus the ones that are about this
    /// container rather than the unit. Skipped where systemd-analyze is absent.
    fn complaints(unit: &str) -> Option<Vec<String>> {
        let probe = std::process::Command::new("systemd-analyze")
            .arg("--version")
            .output()
            .ok()?;
        if !probe.status.success() {
            return None;
        }

        let dir = std::env::temp_dir().join(format!(
            "omnia-unit-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("omnia-test.service");
        std::fs::write(&path, unit).unwrap();

        let output = std::process::Command::new("systemd-analyze")
            .arg("verify")
            .arg(&path)
            .output()
            .expect("systemd-analyze runs");
        let _ = std::fs::remove_dir_all(&dir);

        Some(
            String::from_utf8_lossy(&output.stderr)
                .lines()
                .filter(|line| !line.trim().is_empty())
                // The binary genuinely is not installed here; that is the
                // container's problem, not the unit's.
                .filter(|line| !line.contains("is not executable"))
                .map(str::to_string)
                .collect(),
        )
    }

    fn unit_with(devices: &[&str], network: bool) -> String {
        Unit {
            name: "omnia-cap-test".into(),
            description: "A generated capability".into(),
            kind: UnitKind::OneShot,
            argv: vec!["/usr/bin/true".into()],
            permissions: Permissions {
                read_paths: vec!["/home/sam/Pictures".into()],
                write_paths: vec!["/var/backups/pictures".into()],
                devices: devices.iter().map(|d| (*d).to_string()).collect(),
                network,
            },
        }
        .render_service()
    }

    #[test]
    fn systemd_understands_every_directive_in_a_generated_unit() {
        let Some(complaints) = complaints(&unit_with(&[], false)) else {
            return;
        };
        assert!(
            complaints.is_empty(),
            "systemd does not understand the generated unit:\n{}",
            complaints.join("\n")
        );
    }

    #[test]
    fn systemd_understands_a_driver_unit_too() {
        // DeviceAllow is exactly the kind of directive that is accepted as text
        // and dropped as policy if its argument is malformed.
        let Some(complaints) = complaints(&unit_with(&["/dev/bus/usb/001/004"], false)) else {
            return;
        };
        assert!(
            complaints.is_empty(),
            "systemd does not understand the driver unit:\n{}",
            complaints.join("\n")
        );
    }

    #[test]
    fn no_syscall_group_is_silently_discarded() {
        // The specific failure: "System call ~@privileged is not known,
        // ignoring". It is a warning, so the unit still loads, and the only
        // symptom is that the sandbox is weaker than the file says.
        let Some(complaints) = complaints(&unit_with(&[], true)) else {
            return;
        };
        let discarded: Vec<&String> = complaints
            .iter()
            .filter(|line| line.contains("is not known"))
            .collect();
        assert!(
            discarded.is_empty(),
            "systemd is discarding part of the sandbox:\n{discarded:?}"
        );
    }
}

#[cfg(test)]
mod device_tests {
    use super::*;

    fn driver_unit(devices: &[&str]) -> String {
        Unit {
            name: "omnia-cap-driver-1234-5678".into(),
            description: "Drive 1234:5678".into(),
            kind: UnitKind::OneShot,
            argv: vec!["/usr/lib/omnia/drivers/thing".into()],
            permissions: Permissions {
                read_paths: Vec::new(),
                write_paths: Vec::new(),
                devices: devices.iter().map(|d| (*d).to_string()).collect(),
                network: false,
            },
        }
        .render_service()
    }

    #[test]
    fn a_capability_with_no_devices_gets_a_private_dev() {
        let unit = driver_unit(&[]);
        assert!(unit.contains("PrivateDevices=yes"), "{unit}");
        assert!(!unit.contains("DeviceAllow="), "{unit}");
    }

    #[test]
    fn a_driver_names_exactly_its_own_device_and_nothing_else() {
        // The property rung 5 rests on. A unit that names one node is a unit an
        // operator can approve by reading it.
        let unit = driver_unit(&["/dev/bus/usb/001/004"]);
        let allows: Vec<&str> = unit
            .lines()
            .filter(|line| line.starts_with("DeviceAllow="))
            .collect();
        assert_eq!(allows, vec!["DeviceAllow=/dev/bus/usb/001/004 rw"]);
        assert!(unit.contains("DevicePolicy=closed"), "{unit}");
    }

    #[test]
    fn a_driver_does_not_get_private_devices() {
        // The mistake that would make a generated driver fail in a way nobody
        // could diagnose: PrivateDevices=yes mounts a /dev without the device,
        // so the driver opens its own node and gets ENOENT rather than EPERM.
        let unit = driver_unit(&["/dev/i2c-1"]);
        // Directives, not prose: the unit explains in a comment why
        // PrivateDevices=yes is wrong here, and matching the text would fail on
        // the explanation.
        let directives: Vec<&str> = unit
            .lines()
            .filter(|line| line.starts_with("PrivateDevices="))
            .collect();
        assert_eq!(
            directives,
            vec!["PrivateDevices=no"],
            "the device would be hidden from its own driver:\n{unit}"
        );
    }

    #[test]
    fn everything_else_stays_locked_down_for_a_driver() {
        // Needing a device is not a reason to relax anything else. A driver is
        // the least trustworthy thing on the machine, not the most.
        let unit = driver_unit(&["/dev/bus/usb/001/004"]);
        for directive in [
            "NoNewPrivileges=yes",
            "CapabilityBoundingSet=",
            "ProtectSystem=strict",
            "ProtectKernelModules=yes",
            "MemoryDenyWriteExecute=yes",
            "PrivateNetwork=yes",
            "RestrictRealtime=yes",
        ] {
            assert!(
                unit.contains(directive),
                "{directive} missing from:\n{unit}"
            );
        }
    }

    #[test]
    fn a_driver_keeps_the_syscalls_it_needs_to_talk_to_its_device() {
        // ioctl is how usbfs and I2C are driven. It lives in @system-service,
        // and none of the removed groups contains it -- a filter that dropped
        // it would leave a driver that can open its device and do nothing.
        let unit = driver_unit(&["/dev/i2c-1"]);
        let filter = unit
            .lines()
            .find(|line| line.starts_with("SystemCallFilter="))
            .expect("a filter is set");
        assert!(filter.contains("@system-service"), "{filter}");
        assert!(!filter.contains("~@io-event"), "{filter}");
    }

    #[test]
    fn several_devices_each_get_their_own_line() {
        // An I2C sensor behind a USB bridge legitimately needs both.
        let unit = driver_unit(&["/dev/bus/usb/001/004", "/dev/i2c-1"]);
        assert!(
            unit.contains("DeviceAllow=/dev/bus/usb/001/004 rw"),
            "{unit}"
        );
        assert!(unit.contains("DeviceAllow=/dev/i2c-1 rw"), "{unit}");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn unit(read: &[&str], write: &[&str], network: bool) -> Unit {
        Unit {
            name: "omnia-cap-backup-pictures".into(),
            description: "Back up ~/Pictures nightly".into(),
            kind: UnitKind::Scheduled,
            argv: vec![
                "/usr/bin/rsync".into(),
                "--archive".into(),
                "/home/sam/Pictures/".into(),
                "/var/backups/pictures/".into(),
            ],
            permissions: Permissions {
                read_paths: read.iter().map(|s| s.to_string()).collect(),
                write_paths: write.iter().map(|s| s.to_string()).collect(),
                devices: Vec::new(),
                network,
            },
        }
    }

    #[test]
    fn the_hardening_directives_are_present() {
        let rendered =
            unit(&["/home/sam/Pictures"], &["/var/backups/pictures"], false).render_service();
        for directive in [
            "ProtectSystem=strict",
            "NoNewPrivileges=yes",
            "CapabilityBoundingSet=",
            "PrivateDevices=yes",
            "RestrictNamespaces=yes",
            "MemoryDenyWriteExecute=yes",
            "SystemCallArchitectures=native",
            "ProtectKernelModules=yes",
        ] {
            assert!(
                rendered.contains(directive),
                "missing {directive}:\n{rendered}"
            );
        }
    }

    #[test]
    fn declared_paths_become_read_only_and_read_write() {
        let rendered =
            unit(&["/home/sam/Pictures"], &["/var/backups/pictures"], false).render_service();
        assert!(
            rendered.contains("ReadOnlyPaths=/home/sam/Pictures"),
            "{rendered}"
        );
        assert!(
            rendered.contains("ReadWritePaths=/var/backups/pictures"),
            "{rendered}"
        );
    }

    #[test]
    fn no_network_means_no_network_namespace() {
        let rendered = unit(&["/home/sam/Pictures"], &["/var/backups"], false).render_service();
        assert!(rendered.contains("PrivateNetwork=yes"));
        assert!(rendered.contains("IPAddressDeny=any"));
    }

    #[test]
    fn declared_network_opens_exactly_that() {
        let rendered = unit(&[], &["/var/cache/x"], true).render_service();
        assert!(rendered.contains("PrivateNetwork=no"));
        assert!(
            !rendered.contains("IPAddressDeny=any"),
            "must not deny what was declared"
        );
    }

    #[test]
    fn protect_home_is_read_only_when_home_is_only_read() {
        let rendered =
            unit(&["/home/sam/Pictures"], &["/var/backups/pictures"], false).render_service();
        assert!(rendered.contains("ProtectHome=read-only"), "{rendered}");
    }

    #[test]
    fn protect_home_is_off_when_writing_under_home() {
        // read-only here would produce a unit that starts fine and fails every
        // run with EROFS -- a silent failure, which is why this is computed.
        let rendered =
            unit(&["/home/sam/Pictures"], &["/home/sam/backups"], false).render_service();
        assert!(rendered.contains("ProtectHome=no"), "{rendered}");
    }

    #[test]
    fn protect_home_hides_home_when_it_is_not_needed_at_all() {
        let rendered = unit(&["/srv/data"], &["/var/backups"], false).render_service();
        assert!(rendered.contains("ProtectHome=yes"), "{rendered}");
    }

    #[test]
    fn argv_with_spaces_is_quoted_for_systemd() {
        let mut unit = unit(&[], &["/var/backups"], false);
        unit.argv = vec!["/usr/bin/rsync".into(), "/home/sam/My Photos/".into()];
        let rendered = unit.render_service();
        assert!(
            rendered.contains(r#"ExecStart=/usr/bin/rsync "/home/sam/My Photos/""#),
            "{rendered}"
        );
    }

    #[test]
    fn paths_with_spaces_are_quoted_in_directives() {
        let rendered = unit(&["/home/sam/My Photos"], &["/var/backups"], false).render_service();
        assert!(
            rendered.contains(r#"ReadOnlyPaths="/home/sam/My Photos""#),
            "{rendered}"
        );
    }

    #[test]
    fn a_scheduled_unit_gets_a_persistent_jittered_timer() {
        let rendered = unit(&[], &["/var/backups"], false)
            .render_timer("*-*-* 02:00:00")
            .unwrap();
        assert!(rendered.contains("OnCalendar=*-*-* 02:00:00"));
        // A machine asleep at 02:00 still wants its backup.
        assert!(rendered.contains("Persistent=yes"));
        // Otherwise every machine in a fleet fires at exactly 02:00:00.
        assert!(rendered.contains("RandomizedDelaySec=300"));
    }

    #[test]
    fn a_one_shot_capability_has_no_timer() {
        let mut unit = unit(&[], &["/var/backups"], false);
        unit.kind = UnitKind::OneShot;
        assert!(unit.render_timer("*-*-* 02:00:00").is_none());
    }
}
