//! Rendering a systemd unit from a permission set.

use std::fmt::Write as _;

use omnia_parts::Permissions;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnitKind {
    /// Runs once when started.
    OneShot,
    /// Runs on a timer. The timer unit is rendered separately.
    Scheduled,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Unit {
    pub name: String,
    pub description: String,
    pub kind: UnitKind,
    pub argv: Vec<String>,
    pub permissions: Permissions,
}

impl Unit {
    /// Render the `.service` file.
    ///
    /// Every directive here is deliberate, and the ones that are absent are
    /// deliberate too. The comments in the output are for the operator reading
    /// `systemctl cat`, not for us.
    pub fn render_service(&self) -> String {
        let mut out = String::new();

        let _ = writeln!(
            out,
            "# Generated by Omnia. Do not edit: regenerated on rebuild."
        );
        let _ = writeln!(
            out,
            "# Reach is derived from the parts used, not declared by a model."
        );
        let _ = writeln!(out, "[Unit]");
        let _ = writeln!(out, "Description={}", self.description);
        let _ = writeln!(out, "Documentation=man:omni(1)");
        let _ = writeln!(out);

        let _ = writeln!(out, "[Service]");
        let _ = writeln!(out, "Type=oneshot");
        let _ = writeln!(out, "ExecStart={}", quote_argv(&self.argv));
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- filesystem ---");
        // strict: everything read-only except /dev, /proc, /sys, then the
        // write paths are punched back in explicitly below.
        let _ = writeln!(out, "ProtectSystem=strict");
        let _ = writeln!(out, "ProtectHome={}", self.protect_home());
        if !self.permissions.read_paths.is_empty() {
            let _ = writeln!(out, "ReadOnlyPaths={}", join(&self.permissions.read_paths));
        }
        if !self.permissions.write_paths.is_empty() {
            let _ = writeln!(
                out,
                "ReadWritePaths={}",
                join(&self.permissions.write_paths)
            );
        }
        let _ = writeln!(out, "PrivateTmp=yes");
        let _ = writeln!(out, "ProtectProc=invisible");
        let _ = writeln!(out, "ProcSubset=pid");
        let _ = writeln!(out, "UMask=0077");
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- network ---");
        if self.permissions.network {
            let _ = writeln!(out, "# this capability declared network access");
            let _ = writeln!(out, "PrivateNetwork=no");
            let _ = writeln!(out, "RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX");
        } else {
            // The strongest available statement: no network namespace at all.
            let _ = writeln!(out, "PrivateNetwork=yes");
            let _ = writeln!(out, "RestrictAddressFamilies=AF_UNIX");
            let _ = writeln!(out, "IPAddressDeny=any");
        }
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- privilege ---");
        let _ = writeln!(out, "NoNewPrivileges=yes");
        let _ = writeln!(out, "CapabilityBoundingSet=");
        let _ = writeln!(out, "AmbientCapabilities=");
        let _ = writeln!(out, "RestrictSUIDSGID=yes");
        let _ = writeln!(out, "PrivateUsers=yes");
        let _ = writeln!(out, "DynamicUser=no");
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- kernel ---");
        let _ = writeln!(out, "ProtectKernelTunables=yes");
        let _ = writeln!(out, "ProtectKernelModules=yes");
        let _ = writeln!(out, "ProtectKernelLogs=yes");
        let _ = writeln!(out, "ProtectControlGroups=yes");
        let _ = writeln!(out, "ProtectClock=yes");
        let _ = writeln!(out, "ProtectHostname=yes");
        let _ = writeln!(out, "RestrictNamespaces=yes");
        let _ = writeln!(out, "RestrictRealtime=yes");
        let _ = writeln!(out, "LockPersonality=yes");
        let _ = writeln!(out, "MemoryDenyWriteExecute=yes");
        let _ = writeln!(out);

        let _ = writeln!(out, "# --- devices and syscalls ---");
        let _ = writeln!(out, "PrivateDevices=yes");
        let _ = writeln!(out, "DevicePolicy=closed");
        let _ = writeln!(out, "SystemCallArchitectures=native");
        // @system-service minus the groups a data-moving job never needs.
        let _ = writeln!(
            out,
            "SystemCallFilter=@system-service ~@privileged ~@resources ~@mount ~@debug ~@module"
        );
        let _ = writeln!(out, "SystemCallErrorNumber=EPERM");

        out
    }

    /// Render the `.timer` file. `None` for capabilities that are not scheduled.
    pub fn render_timer(&self, calendar: &str) -> Option<String> {
        if self.kind != UnitKind::Scheduled {
            return None;
        }
        let mut out = String::new();
        let _ = writeln!(
            out,
            "# Generated by Omnia. Do not edit: regenerated on rebuild."
        );
        let _ = writeln!(out, "[Unit]");
        let _ = writeln!(out, "Description={} (timer)", self.description);
        let _ = writeln!(out);
        let _ = writeln!(out, "[Timer]");
        let _ = writeln!(out, "OnCalendar={calendar}");
        // A machine that was asleep at 02:00 still wants its backup.
        let _ = writeln!(out, "Persistent=yes");
        // Without this every machine in a fleet runs at exactly 02:00:00.
        let _ = writeln!(out, "RandomizedDelaySec=300");
        let _ = writeln!(out);
        let _ = writeln!(out, "[Install]");
        let _ = writeln!(out, "WantedBy=timers.target");
        Some(out)
    }

    /// `ProtectHome` depends on where the capability needs to write.
    ///
    /// Getting this wrong is silent: `read-only` with a write target under home
    /// produces a unit that starts fine and fails every run with EROFS. So the
    /// value is computed from the paths rather than fixed.
    fn protect_home(&self) -> &'static str {
        let writes_under_home = self
            .permissions
            .write_paths
            .iter()
            .any(|p| is_under_home(p));
        let reads_under_home = self.permissions.read_paths.iter().any(|p| is_under_home(p));

        if writes_under_home {
            // ReadWritePaths punches through, but ProtectHome must not be
            // masking the tree in the first place.
            "no"
        } else if reads_under_home {
            "read-only"
        } else {
            // Nothing in home is needed, so hide it entirely.
            "yes"
        }
    }
}

fn is_under_home(path: &str) -> bool {
    path.starts_with("/home/") || path.starts_with("/root/") || path.starts_with("~/")
}

/// Paths in systemd directives are space-separated; a path containing a space
/// is quoted.
fn join(paths: &[String]) -> String {
    paths
        .iter()
        .map(|p| {
            if p.contains(' ') {
                format!("\"{p}\"")
            } else {
                p.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

/// Render argv for `ExecStart`. systemd splits on whitespace unless quoted, so
/// any element containing a space or a quote is quoted and escaped.
fn quote_argv(argv: &[String]) -> String {
    argv.iter()
        .map(|arg| {
            if arg.contains(' ') || arg.contains('"') || arg.contains('\\') {
                format!("\"{}\"", arg.replace('\\', "\\\\").replace('"', "\\\""))
            } else {
                arg.clone()
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn unit(read: &[&str], write: &[&str], network: bool) -> Unit {
        Unit {
            name: "omnia-cap-backup-pictures".into(),
            description: "Back up ~/Pictures nightly".into(),
            kind: UnitKind::Scheduled,
            argv: vec![
                "/usr/bin/rsync".into(),
                "--archive".into(),
                "/home/sam/Pictures/".into(),
                "/var/backups/pictures/".into(),
            ],
            permissions: Permissions {
                read_paths: read.iter().map(|s| s.to_string()).collect(),
                write_paths: write.iter().map(|s| s.to_string()).collect(),
                network,
            },
        }
    }

    #[test]
    fn the_hardening_directives_are_present() {
        let rendered =
            unit(&["/home/sam/Pictures"], &["/var/backups/pictures"], false).render_service();
        for directive in [
            "ProtectSystem=strict",
            "NoNewPrivileges=yes",
            "CapabilityBoundingSet=",
            "PrivateDevices=yes",
            "RestrictNamespaces=yes",
            "MemoryDenyWriteExecute=yes",
            "SystemCallArchitectures=native",
            "ProtectKernelModules=yes",
        ] {
            assert!(
                rendered.contains(directive),
                "missing {directive}:\n{rendered}"
            );
        }
    }

    #[test]
    fn declared_paths_become_read_only_and_read_write() {
        let rendered =
            unit(&["/home/sam/Pictures"], &["/var/backups/pictures"], false).render_service();
        assert!(
            rendered.contains("ReadOnlyPaths=/home/sam/Pictures"),
            "{rendered}"
        );
        assert!(
            rendered.contains("ReadWritePaths=/var/backups/pictures"),
            "{rendered}"
        );
    }

    #[test]
    fn no_network_means_no_network_namespace() {
        let rendered = unit(&["/home/sam/Pictures"], &["/var/backups"], false).render_service();
        assert!(rendered.contains("PrivateNetwork=yes"));
        assert!(rendered.contains("IPAddressDeny=any"));
    }

    #[test]
    fn declared_network_opens_exactly_that() {
        let rendered = unit(&[], &["/var/cache/x"], true).render_service();
        assert!(rendered.contains("PrivateNetwork=no"));
        assert!(
            !rendered.contains("IPAddressDeny=any"),
            "must not deny what was declared"
        );
    }

    #[test]
    fn protect_home_is_read_only_when_home_is_only_read() {
        let rendered =
            unit(&["/home/sam/Pictures"], &["/var/backups/pictures"], false).render_service();
        assert!(rendered.contains("ProtectHome=read-only"), "{rendered}");
    }

    #[test]
    fn protect_home_is_off_when_writing_under_home() {
        // read-only here would produce a unit that starts fine and fails every
        // run with EROFS -- a silent failure, which is why this is computed.
        let rendered =
            unit(&["/home/sam/Pictures"], &["/home/sam/backups"], false).render_service();
        assert!(rendered.contains("ProtectHome=no"), "{rendered}");
    }

    #[test]
    fn protect_home_hides_home_when_it_is_not_needed_at_all() {
        let rendered = unit(&["/srv/data"], &["/var/backups"], false).render_service();
        assert!(rendered.contains("ProtectHome=yes"), "{rendered}");
    }

    #[test]
    fn argv_with_spaces_is_quoted_for_systemd() {
        let mut unit = unit(&[], &["/var/backups"], false);
        unit.argv = vec!["/usr/bin/rsync".into(), "/home/sam/My Photos/".into()];
        let rendered = unit.render_service();
        assert!(
            rendered.contains(r#"ExecStart=/usr/bin/rsync "/home/sam/My Photos/""#),
            "{rendered}"
        );
    }

    #[test]
    fn paths_with_spaces_are_quoted_in_directives() {
        let rendered = unit(&["/home/sam/My Photos"], &["/var/backups"], false).render_service();
        assert!(
            rendered.contains(r#"ReadOnlyPaths="/home/sam/My Photos""#),
            "{rendered}"
        );
    }

    #[test]
    fn a_scheduled_unit_gets_a_persistent_jittered_timer() {
        let rendered = unit(&[], &["/var/backups"], false)
            .render_timer("*-*-* 02:00:00")
            .unwrap();
        assert!(rendered.contains("OnCalendar=*-*-* 02:00:00"));
        // A machine asleep at 02:00 still wants its backup.
        assert!(rendered.contains("Persistent=yes"));
        // Otherwise every machine in a fleet fires at exactly 02:00:00.
        assert!(rendered.contains("RandomizedDelaySec=300"));
    }

    #[test]
    fn a_one_shot_capability_has_no_timer() {
        let mut unit = unit(&[], &["/var/backups"], false);
        unit.kind = UnitKind::OneShot;
        assert!(unit.render_timer("*-*-* 02:00:00").is_none());
    }
}
